type: SwinTransformer
name: test
context_size: 1
img_height: ${data.height}
img_width: ${data.width}
patch_size: 1
constant_channels: 4
prescribed_channels: 1
prognostic_channels: 8
embed_dim: 96
#depths: [2, 2, 6, 2]
#num_heads: [3, 6, 12, 24]
depths: [4, 4]
num_heads: [4, 4]
mlp_ratio: 4
qkv_bias: True
qk_scale: null
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.2
norm_layer: nn.LayerNorm
ape: False
patch_norm: True
frozen_stages: -1
use_checkpoint: False
